{{- $username := coalesce .Values.postgresql.postgresqlUsername .Values.pgClient.external.username "postgres" -}}
{{- $password := include "hasura.postgresPassword" . -}}
{{- $port := (coalesce .Values.postgresql.servicePort .Values.pgClient.external.port 5432) | int -}}
{{- $host := ternary (printf "%s-postgresql" .Release.Name) .Values.pgClient.external.host .Values.postgresql.enabled  -}}
{{- $db := coalesce .Values.postgresql.postgresqlDatabase .Values.pgClient.external.database "hasura" -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
data:
  postgresql-password: {{ $password | b64enc | quote }}
  databaseUrl: {{ (printf "postgres://%s:%s@%s:%d/%s" $username $password $host $port $db) | b64enc | quote }}
