apiVersion: v1
kind: Service
metadata:
  name: {{ include "hasura.fullname" . }}
  labels: {{- include "hasura.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector: {{- include "hasura.selectorLabels" . | nindent 4 }}
