annotations:
  artifacthub.io/changes: '- fix: correct configmap name'
apiVersion: v2
appVersion: v1.3.3.cli-migrations-v2
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 8.10.13
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 0.7.1
description: Hasura GraphQL Engine
home: https://platy.dev/charts/hasura.html
icon: https://raw.githubusercontent.com/hasura/graphql-engine/master/assets/brand/hasura_icon_blue.svg
keywords:
- hasura
- graphql
- postgresql
name: hasura
sources:
- https://github.com/platyplus/platydev/tree/master/charts/hasura
- https://github.com/hasura/graphql-engine
type: application
version: 0.1.6
