{{- if .Values.managementcenter.configurationFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hazelcast-jet-management-center.fullname" . }}-configuration
  labels:
    app: {{ template "hazelcast-jet.name" . }}
    chart: {{ template "hazelcast-jet.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{- range $key, $val := .Values.managementcenter.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
