## deployment-replication/rbac.yaml
{{- if .Values.DeploymentReplication.Create }}
{{- if .Values.RBAC.Create }}

## Cluster role granting access to ArangoDeploymentReplication resources.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" .Release.Name "deployment-replications" | trunc 63 | trimSuffix "-" }}
rules:
- apiGroups: ["replication.database.arangodb.com"]
  resources: ["arangodeploymentreplications"]
  verbs: ["*"]

---

## Cluster role granting access to all resources needed by the ArangoDeploymentReplication operator.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" .Release.Name "deployment-replication-operator" | trunc 63 | trimSuffix "-" }}
rules:
- apiGroups: ["replication.database.arangodb.com"]
  resources: ["arangodeploymentreplications"]
  verbs: ["*"]
- apiGroups: ["database.arangodb.com"]
  resources: ["arangodeployments"]
  verbs: ["get"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get"]

---

## Bind the cluster role granting access to ArangoDeploymentReplication resources
## to the default service account of the configured namespace.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ printf "%s-%s" .Release.Name "deployment-replications" | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-%s" .Release.Name "deployment-replications" | trunc 63 | trimSuffix "-" }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.DeploymentReplication.User.ServiceAccountName }}
  namespace: {{ .Release.Namespace }}

---

## Bind the cluster role granting access to all resources needed by 
## the ArangoDeploymentReplication operator to the default service account
## the is being used to run the operator deployment.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s" .Release.Name "deployment-replication-operator" | trunc 63 | trimSuffix "-" }}-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-%s" .Release.Name "deployment-replication-operator" | trunc 63 | trimSuffix "-" }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.DeploymentReplication.Operator.ServiceAccountName }}
  namespace: {{ .Release.Namespace }}

{{- end }}
{{- end }}


---

## deployment-replication/deployment-replication.yaml
{{- if .Values.DeploymentReplication.Create }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: arango-deployment-replication-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: arango-deployment-replication-operator
        app: arango-deployment-replication-operator
    spec:
      serviceAccountName: {{ .Values.DeploymentReplication.Operator.ServiceAccountName }}
      containers:
      - name: operator
        imagePullPolicy: {{ .Values.ImagePullPolicy }}
        image: {{ .Values.Image }}
        args:
          - --operator.deployment-replication
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: metrics
          containerPort: 8528
        livenessProbe:
          httpGet:
            path: /health
            port: 8528
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready/deployment-replication
            port: 8528
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5

{{- end }}


---

## deployment-replication/service.yaml
{{- if .Values.DeploymentReplication.Create }}

apiVersion: v1
kind: Service
metadata:
  name: arango-deployment-replication-operator
  namespace: {{ .Release.Namespace }}
  labels:
    name: arango-deployment-replication-operator
    app: arango-deployment-replication-operator
spec:
  ports:
  - name: server
    port: 8528
    protocol: TCP
    targetPort: 8528
  selector:
    name: arango-deployment-replication-operator
    app: arango-deployment-replication-operator
    role: leader
  type: {{ .Values.DeploymentReplication.Operator.ServiceType }}

{{- end }}

